### ISSUE TITLE
Tests for API

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/torn#12]
Find a way to write tests for torn.api module.

**Comment by h93xV2** [comment]
I am working on this

**Comment by shubhodeep9** [comment]
@h93xV2 yo

**Comment by h93xV2** [comment]
Seems I don't have enough time for this

**Comment by ba11b0y** [comment]
@shubhodeep9 Does `nosetests` work?

**Comment by shubhodeep9** [comment]
@invinciblycool anything will work as long as it can support a good coverage for our needs.
Let's divide the tests into segments.
- `unit tests`
- `acceptance`
- and anything that you can come up with.
Let's make a checklist of that in the issue, so that we can cover them.

**Comment by ba11b0y** [comment]
@shubhodeep9 While writing  a test for the `runHandler`, I ran into a problem. It indirectly invokes the `run()` function which triggers a `ioloop` due to which I am unable to test by sending a GET request since the control is never returned back.
Also I have written very basic tests for the CLI, if you could have a look at them [here](https://github.com/invinciblycool/torn/tree/add-tests) so that I may go ahead with the rest of the tests if the style suits.

**Comment by ba11b0y** [comment]
@shubhodeep9 Ping!

**Comment by shubhodeep9** [comment]
Hey @invinciblycool really sorry for being away.
But before we move ahead with anything, I want this #28 to be implemented at priority.
Give me a day's time, and will release an update for contribution to the repo.
